global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:7072']
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:7073']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
